// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2cLeNNjW-g23mEYl59-3AnRnpE94QIcg',
    appId: '1:242894220546:web:6c99d20cd9a862578ee61b',
    messagingSenderId: '242894220546',
    projectId: 'tudu-6f3cd',
    authDomain: 'tudu-6f3cd.firebaseapp.com',
    storageBucket: 'tudu-6f3cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq0salHgOHfBBVNAc-ZlhGQBMZGK8GZO0',
    appId: '1:242894220546:android:3a66c0db5ca103d38ee61b',
    messagingSenderId: '242894220546',
    projectId: 'tudu-6f3cd',
    storageBucket: 'tudu-6f3cd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2cLeNNjW-g23mEYl59-3AnRnpE94QIcg',
    appId: '1:242894220546:web:8d815aa04298e6da8ee61b',
    messagingSenderId: '242894220546',
    projectId: 'tudu-6f3cd',
    authDomain: 'tudu-6f3cd.firebaseapp.com',
    storageBucket: 'tudu-6f3cd.firebasestorage.app',
  );
}
